package me.nithans.decoration.dal.mapper.decoration;

import java.util.List;
import me.nithans.decoration.dal.domain.decoration.Group;
import me.nithans.decoration.dal.domain.decoration.GroupCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_group
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    long countByExample(GroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_group
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    int deleteByExample(GroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_group
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_group
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    int insert(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_group
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    int insertSelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_group
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    List<Group> selectByExampleWithRowbounds(GroupCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_group
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    List<Group> selectByExample(GroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_group
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    Group selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_group
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") Group record, @Param("example") GroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_group
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    int updateByExample(@Param("record") Group record, @Param("example") GroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_group
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    int updateByPrimaryKeySelective(Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_group
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    int updateByPrimaryKey(Group record);
}