package me.nithans.decoration.dal.mapper.decoration;

import java.util.List;
import me.nithans.decoration.dal.domain.decoration.HomeBaseInfo;
import me.nithans.decoration.dal.domain.decoration.HomeBaseInfoCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface HomeBaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_baseinfo
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    long countByExample(HomeBaseInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_baseinfo
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    int deleteByExample(HomeBaseInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_baseinfo
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_baseinfo
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    int insert(HomeBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_baseinfo
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    int insertSelective(HomeBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_baseinfo
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    List<HomeBaseInfo> selectByExampleWithRowbounds(HomeBaseInfoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_baseinfo
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    List<HomeBaseInfo> selectByExample(HomeBaseInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_baseinfo
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    HomeBaseInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_baseinfo
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") HomeBaseInfo record, @Param("example") HomeBaseInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_baseinfo
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    int updateByExample(@Param("record") HomeBaseInfo record, @Param("example") HomeBaseInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_baseinfo
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    int updateByPrimaryKeySelective(HomeBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_baseinfo
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    int updateByPrimaryKey(HomeBaseInfo record);
}