package me.nithans.decoration.dal.mapper.decoration;

import java.util.List;
import me.nithans.decoration.dal.domain.decoration.Resource;
import me.nithans.decoration.dal.domain.decoration.ResourceCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_resource
     *
     * @mbg.generated Tue Apr 23 14:14:27 CST 2019
     */
    long countByExample(ResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_resource
     *
     * @mbg.generated Tue Apr 23 14:14:27 CST 2019
     */
    int deleteByExample(ResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_resource
     *
     * @mbg.generated Tue Apr 23 14:14:27 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_resource
     *
     * @mbg.generated Tue Apr 23 14:14:27 CST 2019
     */
    int insert(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_resource
     *
     * @mbg.generated Tue Apr 23 14:14:27 CST 2019
     */
    int insertSelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_resource
     *
     * @mbg.generated Tue Apr 23 14:14:27 CST 2019
     */
    List<Resource> selectByExampleWithRowbounds(ResourceCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_resource
     *
     * @mbg.generated Tue Apr 23 14:14:27 CST 2019
     */
    List<Resource> selectByExample(ResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_resource
     *
     * @mbg.generated Tue Apr 23 14:14:27 CST 2019
     */
    Resource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_resource
     *
     * @mbg.generated Tue Apr 23 14:14:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") Resource record, @Param("example") ResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_resource
     *
     * @mbg.generated Tue Apr 23 14:14:27 CST 2019
     */
    int updateByExample(@Param("record") Resource record, @Param("example") ResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_resource
     *
     * @mbg.generated Tue Apr 23 14:14:27 CST 2019
     */
    int updateByPrimaryKeySelective(Resource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_resource
     *
     * @mbg.generated Tue Apr 23 14:14:27 CST 2019
     */
    int updateByPrimaryKey(Resource record);
}