package me.nithans.decoration.dal.mapper.decoration;

import java.util.List;
import me.nithans.decoration.dal.domain.decoration.Role;
import me.nithans.decoration.dal.domain.decoration.RoleCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_role
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    long countByExample(RoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_role
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    int deleteByExample(RoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_role
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_role
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_role
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_role
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    List<Role> selectByExampleWithRowbounds(RoleCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_role
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    List<Role> selectByExample(RoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_role
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_role
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") Role record, @Param("example") RoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_role
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    int updateByExample(@Param("record") Role record, @Param("example") RoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_role
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_role
     *
     * @mbg.generated Sun Mar 24 17:56:16 CST 2019
     */
    int updateByPrimaryKey(Role record);
}