package me.nithans.decoration.dal.mapper.decoration;

import java.util.List;
import me.nithans.decoration.dal.domain.decoration.UserGroup;
import me.nithans.decoration.dal.domain.decoration.UserGroupCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_user_group
     *
     * @mbg.generated Fri Mar 22 16:15:45 CST 2019
     */
    long countByExample(UserGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_user_group
     *
     * @mbg.generated Fri Mar 22 16:15:45 CST 2019
     */
    int deleteByExample(UserGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_user_group
     *
     * @mbg.generated Fri Mar 22 16:15:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_user_group
     *
     * @mbg.generated Fri Mar 22 16:15:45 CST 2019
     */
    int insert(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_user_group
     *
     * @mbg.generated Fri Mar 22 16:15:45 CST 2019
     */
    int insertSelective(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_user_group
     *
     * @mbg.generated Fri Mar 22 16:15:45 CST 2019
     */
    List<UserGroup> selectByExampleWithRowbounds(UserGroupCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_user_group
     *
     * @mbg.generated Fri Mar 22 16:15:45 CST 2019
     */
    List<UserGroup> selectByExample(UserGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_user_group
     *
     * @mbg.generated Fri Mar 22 16:15:45 CST 2019
     */
    UserGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_user_group
     *
     * @mbg.generated Fri Mar 22 16:15:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserGroup record, @Param("example") UserGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_user_group
     *
     * @mbg.generated Fri Mar 22 16:15:45 CST 2019
     */
    int updateByExample(@Param("record") UserGroup record, @Param("example") UserGroupCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_user_group
     *
     * @mbg.generated Fri Mar 22 16:15:45 CST 2019
     */
    int updateByPrimaryKeySelective(UserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_user_group
     *
     * @mbg.generated Fri Mar 22 16:15:45 CST 2019
     */
    int updateByPrimaryKey(UserGroup record);
}