package me.nithans.decoration.dal.domain.decoration;

import java.io.Serializable;
import java.util.Date;

public class HomeBaseInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_baseinfo.id
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_baseinfo.user_id
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_baseinfo.name
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_baseinfo.type
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_baseinfo.floors_count
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    private Integer floorsCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_baseinfo.all_size
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    private Integer allSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_baseinfo.price
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_baseinfo.create_time
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_baseinfo.update_time
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table decoration_baseinfo
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_baseinfo.id
     *
     * @return the value of decoration_baseinfo.id
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_baseinfo.id
     *
     * @param id the value for decoration_baseinfo.id
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_baseinfo.user_id
     *
     * @return the value of decoration_baseinfo.user_id
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_baseinfo.user_id
     *
     * @param userId the value for decoration_baseinfo.user_id
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_baseinfo.name
     *
     * @return the value of decoration_baseinfo.name
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_baseinfo.name
     *
     * @param name the value for decoration_baseinfo.name
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_baseinfo.type
     *
     * @return the value of decoration_baseinfo.type
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_baseinfo.type
     *
     * @param type the value for decoration_baseinfo.type
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_baseinfo.floors_count
     *
     * @return the value of decoration_baseinfo.floors_count
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public Integer getFloorsCount() {
        return floorsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_baseinfo.floors_count
     *
     * @param floorsCount the value for decoration_baseinfo.floors_count
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public void setFloorsCount(Integer floorsCount) {
        this.floorsCount = floorsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_baseinfo.all_size
     *
     * @return the value of decoration_baseinfo.all_size
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public Integer getAllSize() {
        return allSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_baseinfo.all_size
     *
     * @param allSize the value for decoration_baseinfo.all_size
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public void setAllSize(Integer allSize) {
        this.allSize = allSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_baseinfo.price
     *
     * @return the value of decoration_baseinfo.price
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_baseinfo.price
     *
     * @param price the value for decoration_baseinfo.price
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_baseinfo.create_time
     *
     * @return the value of decoration_baseinfo.create_time
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_baseinfo.create_time
     *
     * @param createTime the value for decoration_baseinfo.create_time
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_baseinfo.update_time
     *
     * @return the value of decoration_baseinfo.update_time
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_baseinfo.update_time
     *
     * @param updateTime the value for decoration_baseinfo.update_time
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_baseinfo
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", name=").append(name);
        sb.append(", type=").append(type);
        sb.append(", floorsCount=").append(floorsCount);
        sb.append(", allSize=").append(allSize);
        sb.append(", price=").append(price);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}