package me.nithans.decoration.dal.domain.decoration;

import java.io.Serializable;
import java.util.Date;

public class Order implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_order.id
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_order.user_id
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_order.order_sn
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    private String orderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_order.create_time
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column decoration_order.update_time
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table decoration_order
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_order.id
     *
     * @return the value of decoration_order.id
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_order.id
     *
     * @param id the value for decoration_order.id
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_order.user_id
     *
     * @return the value of decoration_order.user_id
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_order.user_id
     *
     * @param userId the value for decoration_order.user_id
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_order.order_sn
     *
     * @return the value of decoration_order.order_sn
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_order.order_sn
     *
     * @param orderSn the value for decoration_order.order_sn
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_order.create_time
     *
     * @return the value of decoration_order.create_time
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_order.create_time
     *
     * @param createTime the value for decoration_order.create_time
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column decoration_order.update_time
     *
     * @return the value of decoration_order.update_time
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column decoration_order.update_time
     *
     * @param updateTime the value for decoration_order.update_time
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table decoration_order
     *
     * @mbg.generated Wed Feb 06 00:22:15 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}